spring:
  profiles:
    active: local
  application:
    name: foo-client
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: actuator/status
    health-check-url-path: actuator/health
    secure-port-enabled: false
    non-secure-port-enabled: true
    hostname: localhost
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
